name: Bootcamp Automation

on:
  schedule:
    # Every 30 minutes Mon–Fri (1-5) and Sunday (0)
    - cron: "*/30 * * * 0,1-5"
  workflow_dispatch:   # Allow manual trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Task Scheduler
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          G_USERNAME: ${{ secrets.G_USERNAME }}
          G_REPO: ${{ secrets.G_REPO }}
          G_BRANCH: ${{ secrets.G_BRANCH }}
        run: python scripts/task_runner.py
